WIP: docs/docs-sprint
octopusthink/getmicdrop.com pull request #83
Opened 2021-03-15 22:31 UTC by sarahmonster

Time to flesh out our docs section! I have a few more changes to add to this still.

2022-01-19 22:46 UTC, sarahmonster commented
I think this is ready for review now! The Monterey bug page is obviously a wee bit incomplete, but I can tweak the wording there as needed. @tofumatt if you'd be able to give this a wee review I think it'd be worth getting the changes out one way or another this Friday. 

Now we've got Front all working, I'm going to take a look at hooking up a form at the bottom of the help pages next. 🙌

2022-01-20 18:00 UTC, tofumatt requested changes
This is great! I have a few recommended tweaks/changes but overall this is sooooo much better.

Let's do the "adjust input source in popular apps" in another PR, just so we can get this one shipped quicker 👍🏻

2022-01-20 18:00 UTC, tofumatt commented on src/content/pages/help/monterey-bluetooth.mdx
> +title: Refund policy
```suggestion
title: Monterey Bluetooth Bug
```

2022-01-20 18:10 UTC, tofumatt approved these changes

2022-01-20 18:14 UTC, merged